delete from data_property;
delete from anomaly_check_run;
delete from anomaly_datum_version;
delete from anomaly;
delete from datum_dataset_version;
delete from datum_version;
delete from datum;
delete from id_field_value;
delete from observation;
