drop view uni_anomaly_dto;
drop table data_property;
drop table anomaly_check_run;
drop table anomaly_datum_version;
drop table anomaly;
drop table datum_dataset_version;
drop table datum_version;
drop table datum;
drop table id_field_value;
drop table observation;
drop table param_used;
drop table check_run;
drop table check_param;
drop table bivariate_check;
drop table checks;
drop table correlation;
drop table merge_field;
drop table field_instance;
drop table loader_issue;
drop table study_db_version_config;
drop table study_db_version;
drop table dataset_version_field;
drop table csv_data;
alter table study drop foreign key fk_study_2_field_record;
alter table study drop foreign key fk_study_2_field_phase;
alter table study drop foreign key fk_study_2_field_subject;
alter table study drop foreign key fk_study_2_field_site;
alter table study drop foreign key fk_study_2_field_form;
drop table field;
drop table subject;
drop table site;
drop table dataset_version_stream;
drop table data_stream;
drop table dataset_version;
drop table dataset;
drop table data_location;
drop table study;
